### PR TITLE
refactor(client) 💄 use material for signing in with email

### LINKED ISSUE #83: Material Components and CSS Style
Catniss likes dark mode and colorful buttons. Make the app look like a nice modern app using Google's material guidelines. This is because catniss wants to have a pleasant viewing experience 

Tasks:
- [x] get material components imported
- [x] use material for buttons
- [x] use material for text fields
- [x] spend at least 16 hours on styles (including buttons and text fields)

Acceptance Criteria

- The website should have a consistent design/style

### PR DESCRIPTION
**Pull request by nstringham**
## Before
image
## After
image

### CODE REVIEW

**Comment by nstringham** [comment]
related to #83

**Review by gchamb — DISMISSED** [review]
Everything looks good to me. The only thing is the display name text field clearing after logging out.  If you want to do it or not

You could pass in a function from splash +page.svelte that will clear the display name then change line 95 
`<Item on:SMUI:action={logOut}><Text>Logout</Text></Item>` to 

`
<Item on:SMUI:action={()=>{
 // call logout function underneath
// then call the clearing the display name input field
}}>
    <Text>Logout</Text>
</Item>
`

**Comment by nstringham** [comment]
> The only thing is the display name text field clearing after logging out. If you want to do it or not
> 
> You could pass in a function from splash +page.svelte that will clear the display name then change line 95 `<Item on:SMUI:action={logOut}><Text>Logout</Text></Item>` to
> 
> `<Item on:SMUI:action={()=>{ // call logout function underneath // then call the clearing the display name input field }}> <Text>Logout</Text> </Item>`

I think this is part of #38  and so not a part of this PR

**Comment by Muaad2001** [comment]
Checks out

**Review by Muaad2001 — APPROVED** [review]
checks out

**Pull request merged**
