### PR TITLE
feat(client): 💄 Center error text in lobby.svelte

### PR DESCRIPTION
**Pull request by njumaah**

### CODE REVIEW

**Review by zaverbac — COMMENTED** [review]
I think it looks much better centered. I wonder if the padding should be increased so it's spaced out a little further from the avatars

**Comment by njumaah** [comment]
> I think it looks much better centered. I wonder if the padding should be increased so it's spaced out a little further from the avatars

played around with the padding; 20px seems the best for desktop and mobile

**Comment by njumaah** [comment]
image

**Review by zaverbac — APPROVED** [review]
I think it looks good

**Review by mrjoshua520 — APPROVED** [review]

**Pull request merged**
