### PR TITLE
refactor(functions): ♻️ throw errors instead of returning ErrorResponse

### PR DESCRIPTION
**Pull request by nstringham**
the return type of the callable functions all had issues this PR fixes those issues

this PR also makes functions throw a `HttpsError` instead of returning an object with an `error` property

### CODE REVIEW

**Comment by nstringham** [comment]
related to #93 because I want to get this figured out before I share code between create and join lobby.

**Review by gchamb — APPROVED** [review]
Looks good to me. Tested it in postman and was getting the appropriate messages

**Comment by nstringham** [comment]
I never used postman for firebase before. What URL do you use?

**Comment by gchamb** [comment]
example

Use the request URL and if you want to use it as an authorized user just take the authorization bearer token and use it in postman

**Pull request merged**
