### PR TITLE
feat: ✨ Add Stalker UI and functionality

### LINKED ISSUE #34: Allow Catniss to "stalk" other players (if a match isn't found)
If there is an odd number of players and Catniss cannot find a match that round, she should be able to select a matching pair to view their entire chat log during the chatting phase. so that she doesn't feel left out that round.

**Tasks:**

- [x] Assign random player as stalker after checking odd # of players in Backend
- [x] Display chats as buttons with who is talking with who in Frontend
- [x] Chat buttons should be clickable which will take user to selected chat in Backend
- [x] Stalker should be taken to stalker component in Backend.
- [x] Stalker should join a chat anonymously with read-only function Backend.

**Acceptance Criteria**

- If there is an even number of players in the lobby, this pseudo-role does not exist until there is an odd number.
- If there is an odd number of players, one player selected at random will become a stalker
- If the user is the stalker, they should be shown the current pairs in the round to which they can select which pair they want to stalk
- When stalking, they should be able to see the current chatting between the selected pair
- If the user is not the stalker, they would play the chatting phase normally
- If the user is being stalked, they should not be able to see that they are being stalked until the voting phase
- A hacker shouldn't be able to see if they are being stalked
- A hacker who is the stalker should not be able to stock more than one pair
- A hacker w should not be able to influence who is the stalker

### LINKED ISSUE #83: Material Components and CSS Style
Catniss likes dark mode and colorful buttons. Make the app look like a nice modern app using Google's material guidelines. This is because catniss wants to have a pleasant viewing experience 

Tasks:
- [x] get material components imported
- [x] use material for buttons
- [x] use material for text fields
- [x] spend at least 16 hours on styles (including buttons and text fields)

Acceptance Criteria

- The website should have a consistent design/style

### PR DESCRIPTION
**Pull request by nstringham**
This PR includes all the changes from #65 but also contains some improvements and some Material and CSS

note that this PR does not complete #34 because it does not complete this criteria
> A hacker shouldn't be able to see if they are being stalked

image

### CODE REVIEW

**Review by njumaah — DISMISSED** [review]

**Comment by gchamb** [comment]
Mobile for the icons and names mess up a bit

**Review by gchamb — CHANGES_REQUESTED** [review]
see above

**Comment by gchamb** [comment]
```ts
/**
 * Checks if the user is in a chatroom then returns their chatroom doc
 */
export async function findChatRoom(lobbyId: string, playerId: string) {
  const queryChatRoom = await getDocs(query(getChatRoomCollection(lobbyId), where("pair", "array-contains", playerId)));
  return queryChatRoom.docs[0];
}

export async function findViewerChatRoom(lobbyId: string, viewerId: string) {
  const queryChatRoom = await getDocs(
    query(getChatRoomCollection(lobbyId), where("viewers", "array-contains", viewerId))
  );
  return queryChatRoom.docs[0];
}
```
in chat.ts delete this pls

**Review by gchamb — CHANGES_REQUESTED** [review]
fix build checks

**Review by gchamb — DISMISSED** [review]

**Review by gchamb — APPROVED** [review]

**Pull request merged**
