### PR TITLE
fix(client): 🐛 Fix the create lobby button making multiple lobbies

### LINKED ISSUE #103: Create lobby button should only happen once
## description
The create lobby button can be clicked more than once before the page loads which creates more than one lobby

## steps to reproduce
1. go to https://cat-me-if-you-can-game.web.app
2. Enter a display name
3. Spam the create lobby button

## expected behavior
only one lobby should be created 

## actual behavior
Multiple lobbies are created

## possible cause
"Once" is not being used to modify the button event 
https://svelte.dev/tutorial/event-modifiers

### PR DESCRIPTION
**Pull request by mrjoshua520**
The create lobby button can no longer be spammed to make multiple lobbies

close #103

### CODE REVIEW

**Comment by nstringham** [comment]
can we also do this for join lobby and start game?

**Comment by mrjoshua520** [comment]
> can we also do this for join lobby and start game?

Yep, just added it

**Review by zaverbac — COMMENTED** [review]
Seems like it should work after looking at the documentation for once.

**Review by zaverbac — DISMISSED** [review]
Should work as a solution

**Review by gchamb — DISMISSED** [review]

**Comment by nstringham** [comment]
How about the join button on the join page?

**Review by nstringham — APPROVED** [review]

**Pull request merged**
